name: Build

on:
  workflow_dispatch: # Manual trigger

jobs:
  angular:
    name: Angular Build
    runs-on: self-hosted  # Update if using a specific runner
    strategy:
      matrix:
        node-version: [20] # Use Node.js version 20.x

    steps:
      # Step 1: Checkout the source code
      - name: Checkout the source code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Step 3: Install dependencies with --legacy-peer-deps
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Step 4: Build adminportal and run post-build (PowerShell)
      - name: Build adminportal with PowerShell
        shell: pwsh  # Use PowerShell shell
        run: |
          # Set environment variables
          $env:PROJECT_NAME="adminportal"
          $env:OUTPUT_PATH="frontadmin"
          
          # Run Angular build for the adminportal project
          ng build --project adminportal
          
          # Run post-build script
          node post-build.js
