name: Build

on:
  workflow_dispatch: # Manual trigger

jobs:
  angular:
    name: Angular Build
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20] # Use Node.js version 20.x

    steps:
      # Step 1: Checkout the source code
      - name: Checkout the source code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Step 3: Install dependencies with --legacy-peer-deps
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Step 4: Build the adminportal project
      - name: Build adminportal
        run: npm run build:adminportal

      # Step 5: Install gzip (for tar command)
      - name: Install gzip
        run: sudo apt-get install gzip

      # Step 6: Post-job cleanup (if necessary)
      - name: Post-job cleanup (optional)
        run: |
          tar -cf cache.tgz --exclude cache.tgz -P -C C:/actions-runner1/_work/erp-front/erp-front --files-from manifest.txt --force-local
